web:
  image: ebiztop:v1.2
  restart: always
  ports:
    - "80:80" # web
    - "11122:22" # ssh
    - "33060:3306" # mysql
  volumes:
    - /home/maxwell/eBizTop:/www/eBizTop
    - /home/maxwell/db:/var/lib/mysql
	command: /startup.sh